<?php

/**
 * @file
 * Install deprecated schema for upgrade testing.
 */

declare(strict_types=1);

/**
 * Implements hook_schema().
 */
function site_verify_old_schema_schema() {
  $schema['site_verify'] = [
    'description' => 'Deprecated table used in upgrade testing.',
    'fields' => [
      'svid' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Primary Key: Unique site verification ID.',
      ],
      'engine' => [
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
        'description' => '',
      ],
      'file' => [
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
        'description' => '',
      ],
      'file_contents' => [
        'type' => 'text',
        'not null' => TRUE,
        'size' => 'big',
        'description' => '',
      ],
      'meta' => [
        'type' => 'text',
        'not null' => TRUE,
        'description' => '',
      ],
    ],
    'primary key' => ['svid'],
    'indexes' => [
      'engine' => ['engine'],
    ],
  ];

  return $schema;
}
